[build-system]
requires = ["setuptools >= 61.0",]
build-backend = "setuptools.build_meta"

[project]
name = "go-big-with-github-actions"
description = "Learn how to scale up your data pipelines using GitHub’s powerful Actions framework"
version = "1.0.0"
requires-python = ">=3.9"
dependencies = [
    'exceptiongroup; python_version<"3.11"',
]

[project.optional-dependencies]
test = [
    "pytest-runner",
    "pytest-cov",
    "pytest-env",
    "pytest-vcr",
    "pytest-xdist",
]
docs = [
    "sphinx",
    "sphinx-autobuild",
    "myst-parser",
]
mypy = [
    "mypy",
]