name: First Scraper

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        source:
        [
            al,
            ak,
            az,
            # ca,
            # co,
            # ct,
            # dc,
            # de,
            # fl,
            # ga,
            # hi,
            # ia,
            # id,
            # il,
            # in,
            # ks,
            # ky,
            # la,
            # md,
            # me,
            # mi,
            # mo,
            # mt,
            # ne,
            # nj,
            # nm,
            # ny,
            # oh,
            # ok,
            # or,
            # ri,
            # sc,
            # sd,
            # tn,
            # tx,
            # ut,
            # va,
            # vt,
            # wa,
            # wi,
          ]
    steps:
      - name: Hello world
        run: echo "Hello world"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install scraper
        run: pip install warn-scraper

      - name: Scrape
        run: warn-scraper ${{ matrix.source }} --data-dir ./data/

      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: data
          path: ./data/